name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy-server:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /root/TripTrip
            git fetch origin main
            git rebase origin/main
            pnpm install -F server utils
            pnpm build:utils
            cd apps/server
            pnpm prisma generate
            pnpm prisma migrate deploy
            pnpm build
            pm2 restart main

  deploy-admin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install -F utils admin

      - name: Build admin
        run: pnpm build:utils && pnpm build:admin

      - name: Deploy admin files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "apps/admin/dist/*"
          target: "/www/wwwroot/www.daydreamer.net.cn"
          strip_components: 3

      - name: Clean target directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /www/wwwroot/www.daydreamer.net.cn
            find . -type f -not -path "*/\.*" -delete 