name: Lint and Format

on:
  pull_request:
    branches: [main]

jobs:
  lint-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm format
      - name: Check for changes
        run: |
          git diff --exit-code || (echo "Files were modified by lint/format" && exit 1)